// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package appcfg

// MustString returns String initialized with given value or panics.
func MustString(s string) String {
	var v String
	err := v.Set(s)
	if err != nil {
		panic(err)
	}
	return v
}

// MustNotEmptyString returns NotEmptyString initialized with given value or panics.
func MustNotEmptyString(s string) NotEmptyString {
	var v NotEmptyString
	err := v.Set(s)
	if err != nil {
		panic(err)
	}
	return v
}

// MustEndpoint returns Endpoint initialized with given value or panics.
func MustEndpoint(s string) Endpoint {
	var v Endpoint
	err := v.Set(s)
	if err != nil {
		panic(err)
	}
	return v
}

// MustPort returns Port initialized with given value or panics.
func MustPort(s string) Port {
	var v Port
	err := v.Set(s)
	if err != nil {
		panic(err)
	}
	return v
}

// MustListenPort returns ListenPort initialized with given value or panics.
func MustListenPort(s string) ListenPort {
	var v ListenPort
	err := v.Set(s)
	if err != nil {
		panic(err)
	}
	return v
}
