// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package appcfg

import "fmt"

var _ Value = &String{}

// String implements flag.Value interface.
func (v *String) String() string {
	if v == nil || v.value == nil {
		return ""
	}
	return fmt.Sprint(*v.value)
}

// Set implements flag.Value interface.
func (v *String) Set(s string) error {
	err := v.set(s)
	if err != nil {
		v.value = nil
	}
	return err
}

// Get implements flag.Getter interface.
func (v *String) Get() interface{} {
	if v.value == nil {
		return nil
	}
	return *v.value
}

// Type implements pflag.Value interface.
func (v *String) Type() string {
	return "String"
}

var _ Value = &NotEmptyString{}

// String implements flag.Value interface.
func (v *NotEmptyString) String() string {
	if v == nil || v.value == nil {
		return ""
	}
	return fmt.Sprint(*v.value)
}

// Set implements flag.Value interface.
func (v *NotEmptyString) Set(s string) error {
	err := v.set(s)
	if err != nil {
		v.value = nil
	}
	return err
}

// Get implements flag.Getter interface.
func (v *NotEmptyString) Get() interface{} {
	if v.value == nil {
		return nil
	}
	return *v.value
}

// Type implements pflag.Value interface.
func (v *NotEmptyString) Type() string {
	return "NotEmptyString"
}

var _ Value = &OneOfString{}

// String implements flag.Value interface.
func (v *OneOfString) String() string {
	if v == nil || v.value == nil {
		return ""
	}
	return fmt.Sprint(*v.value)
}

// Set implements flag.Value interface.
func (v *OneOfString) Set(s string) error {
	err := v.set(s)
	if err != nil {
		v.value = nil
	}
	return err
}

// Get implements flag.Getter interface.
func (v *OneOfString) Get() interface{} {
	if v.value == nil {
		return nil
	}
	return *v.value
}

// Type implements pflag.Value interface.
func (v *OneOfString) Type() string {
	return "OneOfString"
}

var _ Value = &Endpoint{}

// String implements flag.Value interface.
func (v *Endpoint) String() string {
	if v == nil || v.value == nil {
		return ""
	}
	return fmt.Sprint(*v.value)
}

// Set implements flag.Value interface.
func (v *Endpoint) Set(s string) error {
	err := v.set(s)
	if err != nil {
		v.value = nil
	}
	return err
}

// Get implements flag.Getter interface.
func (v *Endpoint) Get() interface{} {
	if v.value == nil {
		return nil
	}
	return *v.value
}

// Type implements pflag.Value interface.
func (v *Endpoint) Type() string {
	return "Endpoint"
}

var _ Value = &Port{}

// String implements flag.Value interface.
func (v *Port) String() string {
	if v == nil || v.value == nil {
		return ""
	}
	return fmt.Sprint(*v.value)
}

// Set implements flag.Value interface.
func (v *Port) Set(s string) error {
	err := v.set(s)
	if err != nil {
		v.value = nil
	}
	return err
}

// Get implements flag.Getter interface.
func (v *Port) Get() interface{} {
	if v.value == nil {
		return nil
	}
	return *v.value
}

// Type implements pflag.Value interface.
func (v *Port) Type() string {
	return "Port"
}

var _ Value = &ListenPort{}

// String implements flag.Value interface.
func (v *ListenPort) String() string {
	if v == nil || v.value == nil {
		return ""
	}
	return fmt.Sprint(*v.value)
}

// Set implements flag.Value interface.
func (v *ListenPort) Set(s string) error {
	err := v.set(s)
	if err != nil {
		v.value = nil
	}
	return err
}

// Get implements flag.Getter interface.
func (v *ListenPort) Get() interface{} {
	if v.value == nil {
		return nil
	}
	return *v.value
}

// Type implements pflag.Value interface.
func (v *ListenPort) Type() string {
	return "ListenPort"
}
