// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny


package appcfg

// Value is like Get except it returns zero value and set *err to
// RequiredError if unset.
func (v *StringArray) Value(err *error) (val []string) { //nolint:gocritic // ptrToRefParam.
	if v.Get() == nil {
		*err = &RequiredError{v}
		return val
	}
	return v.values
}


// Value is like Get except it returns zero value and set *err to
// RequiredError if unset.
func (v *StringSlice) Value(err *error) (val []string) { //nolint:gocritic // ptrToRefParam.
	if v.Get() == nil {
		*err = &RequiredError{v}
		return val
	}
	return v.values
}


// Value is like Get except it returns zero value and set *err to
// RequiredError if unset.
func (v *NotEmptyStringArray) Value(err *error) (val []string) { //nolint:gocritic // ptrToRefParam.
	if v.Get() == nil {
		*err = &RequiredError{v}
		return val
	}
	return v.values
}


// Value is like Get except it returns zero value and set *err to
// RequiredError if unset.
func (v *OneOfStringSlice) Value(err *error) (val []string) { //nolint:gocritic // ptrToRefParam.
	if v.Get() == nil {
		*err = &RequiredError{v}
		return val
	}
	return v.values
}


// Value is like Get except it returns zero value and set *err to
// RequiredError if unset.
func (v *EndpointSlice) Value(err *error) (val []string) { //nolint:gocritic // ptrToRefParam.
	if v.Get() == nil {
		*err = &RequiredError{v}
		return val
	}
	return v.values
}
