version: 2.1

jobs:
  test:
    docker:
      - image: "cimg/go:1.15"
        environment:
          GOFLAGS: "-mod=readonly"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-{{ checksum "go.mod" }}-{{ .Branch }}
            - v5-{{ checksum "go.mod" }}-
            - v5-
      - run:
          name: Install tools
          command: |
            GO111MODULE=off go get -u github.com/myitcv/gobin
      - run: gobin -m -run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - run: go test -v -race ./...
      - run: gobin -m -run github.com/mattn/goveralls -service=CircleCI
      - save_cache:
          when: always
          key: v5-{{ checksum "go.mod" }}-{{ .Branch }}
          paths:
            - ~/go/bin/
            - ~/go/pkg/
            - ~/go/src/
            - ~/.cache/go-build/
            - ~/.cache/golangci-lint/
            - ~/.cache/gobin/
            - .gobincache/

workflows:
  default:
    jobs:
      - test
